spring:
  application.name: bookspace-data-loader
  main:
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: main
      username: USERNAME
      password: PASSWORD
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datadump.location:
  author: ABSOLUTE_AUTHOR_FILE_PATH
  works: ABSOLUTE_WORKS_FILE_PATH

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: ID
  region: REGION
  keypspace: main
  application.token: APP_TOKEN